### ISSUE TITLE
Neighbor.ly

### ISSUE THREAD

**Issue by Irio** [opensourcerails/opensourcerails#108]
![neighborly](https://cloud.githubusercontent.com/assets/667753/3269398/67584680-f2ec-11e3-8438-1162e850bef7.png)

Neighborly is a crowdfunding platform, based on [Catarse](https://github.com/catarse/catarse). Although we currently have views tied to [Neighborly product](https://neighbor.ly), we keep getting forked inspiring new crowdfunding projects.

GitHub [neighborly](https://github.com/neighborly)
Demo [neighbor.ly](https://neighbor.ly)

**Comment by mbajur** [comment]
Is that still related? Which repo in here is the main repo for that app? https://github.com/neighborly

**Comment by Irio** [comment]
It's not an open source project anymore.
