### ISSUE TITLE
the Half box

### ISSUE THREAD

**Issue by halfcorp** [opensourcerails/opensourcerails#122]
![new bitmap image](https://cloud.githubusercontent.com/assets/9541964/4927269/2c5e27aa-653a-11e4-9b89-72971f2ffa21.png)

Half box will be an external computer enhancing device designed to make computer run faster by having a high quality graphics card and processor built in it. It will have Steam integrated in it for gaming. It will have gimp, a modding software, and a video recording software built in it. Made for the gamer but it can be used for lots of purposes such as speeding up a work computer or your own personal computer. It will be portable so you can take it with you when you travel. I will have some storage for photos and other miscellaneous stuff. It will have a USB port, a headphone jack, and soon will be integrated for the nerve gear (a prototype game console we are making that simulates the feeling of being in the game console).

**Comment by mbajur** [comment]
Not enough details, please submit at least a repo link.
