### ISSUE TITLE
EasyERP

### ISSUE THREAD

**Issue by 1349** [opensourcerails/opensourcerails#171]
Super Fast Open-Source ERP/CRM/HRM for small business based on Node.js and MongoDB.

Features:
- CRM with companies, contacts, sales pipeline
- PM, Project, portfolio and resource management with kanban
- HRM, human resource management with vacation management, skills & recruiting
- Configurable workflows allow to control the life-cycle of all important objects

We are open for customization requests.
http://easyerp.com

**Comment by mbajur** [comment]
Looks good but what it has to do with ruby/ruby on rails?

I'm closing this.
