### ISSUE TITLE
Helpy

### ISSUE THREAD

**Issue by scott** [opensourcerails/opensourcerails#188]
Fully integrated helpdesk- includes support ticketing, community forums, and multi-language knowledgebase.

http://helpy.io/
http://github.com/scott/helpy

**Comment by mbajur** [comment]
Woah, that's nice!

**Comment by scott** [comment]
Thanks for the words of encouragement :)

**Comment by ivobenedito** [comment]
:+1: Looks pretty good ... makes me wanna try it :)!

**Comment by scott** [comment]
@ivobenedito You should!  I recently got a Portuguese translation too :)  Anything I can do to help out with getting it listed on your awesome site?

**Comment by albertpak** [comment]
can this be used inside of another RoR app or is this a standalone?

**Comment by scott** [comment]
Thanks! It is a standalone app.  I have done some work on a JS widget that could be embedded on other sites though.

**Comment by mbajur** [comment]
I was about to ask for a JS widget. :+1:

**Comment by mbajur** [comment]
I was about to ask for a JS widget. :+1: 

@scott feel free to create a PR with that project data, i believe we're gonna add it instantly.

**Comment by albertpak** [comment]
@scott a JS widget would be great - something like users fill it out and it creates a ticket in the helpy?

**Comment by scott** [comment]
@albertpak Thats exactly what it will be to start at least.  Perhaps in the future it could also include a search bar, but initially i was thinking just a support form.

@mbajur Thanks!  I will work on it when I have a chance.
