### ISSUE TITLE
WakeUpSales - Free Open Source CRM Tool

### ISSUE THREAD

**Issue by andola-dev** [opensourcerails/opensourcerails#205]
WakeUpSales is most innovative Customer Relationship Management application which streamline Sales Activities, Manage Leads, Create Powerful Customer Relationships & Improve Productivity. It’s customization suits to any business size or requirement and more importantly - It’s completely FREE and Open Source.

![wus-1](https://cloud.githubusercontent.com/assets/971183/17809924/76afa608-6637-11e6-959d-4e4773ecd76a.png)

Website - http://www.wakeupsales.org/
Doenload - http://www.wakeupsales.org/free-download.php
Demo - http://demo.wakeupsales.org/

**Comment by c0fe** [comment]
Spam
