### ISSUE TITLE
Church 360° Suite

### ISSUE THREAD

**Issue by lukebooth** [opensourcerails/opensourcerails#213]
A suite of products designed to assist churches manage their day to day chores. The three products — Members, Unite and Ledger — help church workers record attendance, manage offerings, coordinate events, build their public facing website, record their day-to-day finances and so much more! All three are written in Rails with Members and Unite using Backbone.js for the front-end and Ledger using Angular.js.

You can find the marketing pages for them all here: https://www.concordiatechnology.org/church360

**Comment by joshmn** [comment]
Hey Luke, where's the repo hiding for this? I couldn't find it on the marketing pages :(

**Comment by lukebooth** [comment]
I think I just realized that opensourcerails is meant for nice apps where their code is open source, not just that it uses Rails. If that's the case, all three are private repos owned by our company. Sorry!
