### ISSUE TITLE
Opensourcerails.com gone?  Needs renewal?

### ISSUE THREAD

**Issue by scott** [opensourcerails/opensourcerails#217]
Followed a link this morning and got this:

![screen shot 2017-04-15 at 7 50 15 am](https://cloud.githubusercontent.com/assets/14369/25064083/36888a38-21b0-11e7-84b4-4a91811775d0.png)

**Comment by mbajur** [comment]
It's a question to @jacquescrocker which owns the domain. But i don't have contact with him for some time now :(

**Comment by jacquescrocker** [comment]
My apologies. I've just renewed it, it should go back online shortly. Thanks for the heads up!!
