### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fdv** [opensourcerails/opensourcerails#54]
Typo (https://github.com/fdv/typo) is the oldest and most powerful Weblog engine based on Ruby on Rails (it's been around since Rails 0.4 or so). 

It provides everything one need to publish content easily on the Web:

**Fully multi user** with role based feature to manage a multi author blog.

**Powerful plugin system** available both in page, as text filters and as widgets.

**Comprehensive theme support**: every aspect of the blog can be redesigned according to your needs without changing a single line of the core engine.

**Cool API**: Typo supports the various blogging engine APIs so you can publish from desktop clients.

**On demand editor**: Typo supports various editors (visual, plain HTML, Markdown, Textile)

**Comment by mbajur** [comment]
It's now Publify - #140
