### ISSUE TITLE
Catarse

### ISSUE THREAD

**Issue by gregmolnar** [opensourcerails/opensourcerails#60]
I'd like to submit 3 nice opensource project:
Discourse: http://www.discourse.org/
Catarse: https://github.com/danielweinmann/catarse
Selfstarter: http://selfstarter.us/

**Comment by mbajur** [comment]
While the other two are already here, let's convert it to **catarse** request.

https://github.com/catarse/catarse

**Comment by mbajur** [comment]
Actually it's a duplicate of #4
