### ISSUE TITLE
Add TinyMon

### ISSUE THREAD

**Issue by tkadauke** [opensourcerails/opensourcerails#73]
TinyMon (https://github.com/tkadauke/tiny_mon) is an fully open source website monitoring system that comes with a free hosted version (http://mon.tinymon.org). Its purpose is to make sure that your website not only stays online, but also behaves in an expected way. It provides "acceptance tests in the cloud".

From the Website (http://www.tinymon.org):

> Try TinyMon, the revolutionary website monitoring system. Unlike traditional monitoring services, TinyMon lets you periodically test complex scenarios, including:

> * Your website’s signup process, even with “clicking” the activation link sent by email,
> * Your website’s login mechanism,
> * Your online shop’s checkout process,
> * Take periodical screenshots of any page.

There is also an open source iPhone app for TinyMon at https://github.com/tkadauke/TinyMon

**Comment by mbajur** [comment]
Is that still alive?

**Comment by tkadauke** [comment]
I recently lost the hosted version in a datacenter fuckup. I'm also not actively working on it anymore. So feel free to close this issue.
