### ISSUE TITLE
Courseware

### ISSUE THREAD

**Issue by stas** [opensourcerails/opensourcerails#87]
http://open.coursewa.re/

Open Source SaaS Learning Management System to include:
* Classrooms 
* Syllabus
* Customizable UI with subdomains
* Lectures
* Activity streams
* Assignments with quizzes
* Collaborators and students management
* Responses with automatic coverage
* Gradebook
* Localizable
* File Management

Rails 3 engine with a separate web app and an API. Extensive coverage. A simple ember.js app and a simple android app.

**Comment by mbajur** [comment]
Is that still alive?

**Comment by stas** [comment]
The project state now is `as is`, no major interest was seen so it kind of stalled.
